import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import "./global.css";
import Navbar from "./components/navbar";
import { AuthProvider } from "@/lib/client/authProvider";

export const metadata: Metadata = {
  title: "next auth libaray",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
